version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - ledger_network

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - ledger_network

  postgres:
    image: postgres:latest
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ledger_network

  redis:
    image: redis:latest
    container_name: symfony_redis
    ports:
      - "6379:6379"
    networks:
      - ledger_network

volumes:
  pg_data:

networks:
  ledger_network:
