name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      # ✅ Checkout the project
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up PHP with necessary extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: redis, pdo, pdo_pgsql, pdo_sqlite

      # ✅ Cache Composer dependencies
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # ✅ Install dependencies
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      # ✅ Ensure `.env.test` exists
      - name: Create .env.test
        run: |
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=sqlite:///%kernel.project_dir%/data/database.sqlite" >> .env.test
          echo "MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages" >> .env.test

      # ✅ Create SQLite database for testing
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite

      # ✅ Run PHPUnit tests
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: vendor/bin/phpunit
